### ISSUE TITLE
apple_support.run doesn't seem to work when executable is a FilesToRunProvider

### ISSUE THREAD

**Issue by binji** [bazelbuild/apple_support#131]
I'm still pretty new to bazel, so sorry if I'm doing something weird! I'm trying to get [bazel_clang_tidy](https://github.com/erenon/bazel_clang_tidy) working, but patching it to connect it to our copy of LLVM. AIUI, it uses an aspect to generate additional actions for each cc rule. This is almost working, but I started getting errors because the sysroot contained `__BAZEL_XCODE_SDKROOT__`, which I think was being added due to our use of [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj).

I've modified the invocation of `ctx.actions.run` [here](https://github.com/erenon/bazel_clang_tidy/blob/783aa523aafb4a6798a538c61e700b6ed27975a7/clang_tidy/clang_tidy.bzl#L43) to call `apple_support.run` instead, and injected the `"apple"` fragment and appropriate attrs too.

But now I'm seeing bazel file with the following error (truncated):
```
exec: com.google.devtools.build.lib.analysis.FilesToRunProvider@680cb74e: not found
```

It looks like this may be because `apple_support.run` doesn't expect the executable to be a `FilesToRunProvider`.

Is there a good workaround for this, or am I holding it wrong? :-)

**Comment by keith** [comment]
Interesting, I bet it's just an oversight, can you come up with a small sample project for us to iterate on a fix with?

**Comment by keith** [comment]
I think this should fix https://github.com/bazelbuild/apple_support/pull/132

**Comment by binji** [comment]
Thanks for doing this! Sorry for not getting around to writing a sample project

**Comment by keith** [comment]
No worries, let us know if it doesn't work!

**Comment by binji** [comment]
Works perfectly, thanks again!
