### ISSUE TITLE
Getting rid of apple_cc_toolchain

### ISSUE THREAD

**Issue by googlewalt** [bazelbuild/apple_support#298]
We would like to get rid of `apple_cc_toolchain`.  There has been [recent efforts](https://github.com/bazelbuild/bazel/commit/ddcf089bd47c1888854081095cfa32fc1227fe3b) to refector it so that it is more like `cc_toolchain`, to the point where I believe the only remaining difference is the three crosstool variables used by `cc_toolchain_config` to set these environment variables: `XCODE_VERSION_OVERRIDE`, `APPLE_SDK_VERSION_OVERRIDE`, `APPLE_SDK_PLATFORM`.  This information is readily available in `xcode_config`, which is already a dependency of `cc_toolchain_config`, so I believe it should be straightforward to migrate the bazel apple cc toolchain to that.

Once that is done, we should be able to replace all instances of `apple_cc_toolchain` with `cc_toolchain`.

[This change](https://github.com/bazelbuild/bazel/commit/0af1cbae7c4e1b3a3fb9e141b08469e095901d2f) also removes the use on APPLE_SDK_VERSION_OVERRIDE, so that can eventually be dropped also.

**Comment by keith** [comment]
first pass at this, there were a few more variables I had to reproduce, I assume once we merged this we could remove some of the logic from bazel's objc support https://github.com/bazelbuild/apple_support/pull/299
