### ISSUE TITLE
`-no_warn_duplicate_libraries` flag isn't recognized by ldd when overriding the linker

### ISSUE THREAD

**Issue by cerisier** [bazelbuild/apple_support#316]
When using `lld` as the linker using `rules_apple_linker`, linking fails with the following error:
```
unknown argument: -no_warn_duplicate_libraries
```

Happy to provide a patch wherever feels best, even if this means submitting a patch to `llvm`

**Comment by keith** [comment]
quick workaround is to pass `--features=-no_warn_duplicate_libraries`

**Comment by keith** [comment]
here's the upstream lld flag: https://github.com/llvm/llvm-project/pull/86303

note that as of xcode 15 the perf differences with lld decreased a lot, if that was the primary reason you were using it you might want to re-test on your project

**Comment by cerisier** [comment]
Just seeing the reply, sorry about that... Closing the issue since the llvm PR is merged.

As for why we use `lld`, I haven't had time to dig properly why exactly but that's the only way for us to get DWARF info from rust static libraries in the dSYM...
