### ISSUE TITLE
Make the lack of support for the Xcode CLI tools bundle more apparent

### ISSUE THREAD

**Issue by apsaltis-ddog** [bazelbuild/apple_support#353]
We had to update rules_apple as a part of a Bazel update, and we encountered the (documented) issue that only Xcode installs are supported, not the CLI bundle.

While this is fine, and there are ways to disable the related toolchain (`BAZEL_NO_APPLE_CPP_TOOLCHAIN` in the repository environment), it's not readily apparent that this is the case: I only discovered this after reading the code and doing some web searches.

The error message I got was something like this:

```
        File "/private/var/tmp/_bazel_${USER}/d1d980caac4c0e5a356bee44e9b8b9b4/external/local_config_apple_cc/cc_toolchain_config.bzl", line 2507, column 58, in _impl
                enabled = xcode_support.is_xcode_at_least_version(xcode_config, "15.0.0"),
        File "/private/var/tmp/_bazel_${USER}/d1d980caac4c0e5a356bee44e9b8b9b4/external/build_bazel_apple_support/lib/xcode_support.bzl", line 35, column 13, in _is_xcode_at_least_version
                fail("Could not determine Xcode version at all. This likely means Xcode isn't available; " +

Error in fail: Could not determine Xcode version at all. This likely means Xcode isn't available; if you think this is a mistake, please file an issue.
```

I think the following could be helpful:

- Documenting the environment variables to disable this.
- Providing information (even just breadcrumbs) on how to disable the Xcode toolchain in the error message.

WDYT?

This was with Bazel 7.4.1, `rules_apple` 3.13.0, and `apple_support` 1.15.1.  From the looks of it, the code in `apple_support` that causes this failure hasn't changed much since then.

**Comment by keith** [comment]
Thanks for the feedback! I'm just going to try to keep this fixed instead https://github.com/bazelbuild/apple_support/pull/354 we'll see how that goes long term

**Comment by apsaltis-ddog** [comment]
Even better.  Thanks!
