### ISSUE TITLE
Does not work with Bazel 2.1

### ISSUE THREAD

**Issue by Monnoroch** [bazelbuild/apple_support#54]
Error:

```
$ bazel test :all


Traceback (most recent call last):
	File "/.../external/build_bazel_rules_apple/tools/realpath/BUILD", line 9
		_apple_genrule_inner(name = 'realpath_genrule')
	File "/.../external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, in _apple_genrule_impl
		apple_support.run_shell(ctx, <8 more arguments>)
	File "/.../external/build_bazel_apple_support/lib/apple_support.bzl", line 326, in apple_support.run_shell
		ctx.actions.run_shell(<1 more arguments>)
'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_objc_framework_cleanup=false.
```

However, `--incompatible_objc_framework_cleanup=false` doesn't exist:

```
$ bazel test --noincompatible_objc_framework_cleanup :all
ERROR: Unrecognized option: --noincompatible_objc_framework_cleanup
```

It was removed [here](https://github.com/bazelbuild/bazel/commit/50050ae4f4f88877241ebac4f515b487fda86f67).

[Here's](https://github.com/bazelbuild/apple_support/blob/master/lib/apple_support.bzl#L333) the code with the error.

**Comment by thomasvl** [comment]
See the referenced bug on the common in the highlighted code, it still isn't fixed, so the workaround can't be removed.

I'm also not clear on why `--incompatible_objc_framework_cleanup` would control this action behavior, it sounds like the message might be wrong, is some other `--incompatible_*` flag being used?

**Comment by Monnoroch** [comment]
Interesting idea. I can try to find out, but I'm not very familiar with bazel internals.

**Comment by keith** [comment]
Feel free to open a new issue if you still see this with HEAD + a newer bazel release
